image: python:3.11

cache:
  key:
    files:
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - env/

stages:
  - linter
  - pytest
  - data-test
  # - build
  # - deploy

before_script:
  - python --version
  - python -m venv ./env
  - ./env/Scripts/activate

linter_job:
  stage: linter
  tags:
    - test
  script:
    - echo "Starting linters..."
    - pip install flake8
    - flake8 ./src
    - flake8 ./test
    - flake8 ./dags
    - flake8 ./docker

data_quality_job:
  stage: pytest
  tags:
    - test
  script:
    - echo "Starting pytest..."
    - pip install dvc, dvc_s3, pandas, pytest, great_expectations
    - dvc pull
    - pytest ./test

data_pipline_job:
  stage: data-test
  tags:
    - data
  script:
    - echo "Starting DVC check..."
    - pip install dvc, dvc_s3
    - dvc pull
    - dvc repro

# build_job:
#   stage: build
#   tags: 
#     - deploy
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#   script:
#     - echo "Starting build docker image..."

# deploy_job:
#   stage: deploy
#   tags:
#     - deploy
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#   script:
#     - echo "Starting deploy application..."