stages:
  download_raw_data:
    cmd: python src/data/download_raw_data.py
    deps:
      - src/data/download_raw_data.py
    outs:
      - data/raw/houses_dataset.csv

  data_filling:
    cmd: python src/features/data_filling.py data/raw/houses_dataset.csv data/interim/fill_data.csv
    deps:
      - src/features/data_filling.py
      - data/raw/houses_dataset.csv
    outs:
      - data/interim/fill_data.csv

  make_features:
    cmd: python src/features/make_features.py data/interim/fill_data.csv data/interim/features_data.csv
    deps:
      - src/features/make_features.py
      - data/interim/fill_data.csv
    outs:
      - data/interim/features_data.csv

  make_dataset:
    cmd: python src/features/make_dataset.py data/interim/features_data.csv data/processed 85
    deps:
      - src/features/make_dataset.py
      - data/interim/features_data.csv
    outs:
      - data/processed/train_houses.csv
      - data/processed/test_houses.csv
